# Generated by Django 4.2.1 on 2023-05-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='apartmentmodel',
            name='text',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='apartmentmodel',
            name='tags',
            field=models.ManyToManyField(null=True, to='apartment.tags'),
        ),
    ]
