# Generated by Django 4.2.1 on 2023-05-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_tags_alter_apartmentmodel_text_apartmentmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentmodel',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
