# Generated by Django 4.2.1 on 2023-05-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_comment_post'),
        ('home', '0004_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='comnat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apartment.apartmentmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booknow',
            name='rooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=255, null=True),
        ),
    ]
