# Generated by Django 4.2.1 on 2023-05-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_comment_post'),
        ('home', '0005_booknow_comnat_booknow_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AlterField(
            model_name='booknow',
            name='comnat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartmentmodel', verbose_name='apartments'),
        ),
    ]
