# Generated by Django 4.2.1 on 2023-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteInfo', '0002_sidebar'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=252)),
            ],
        ),
    ]
