# Generated by Django 4.2.1 on 2023-05-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteInfo', '0003_newsteller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsteller',
            name='email',
            field=models.CharField(max_length=252),
        ),
    ]
