# Generated by Django 4.2.1 on 2023-05-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteInfo', '0004_alter_newsteller_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
